insert into services (name, slug, category, price_display, base_price, description, fulfillment_type, duration_minutes, rating, reviews_count, features, hero_image)
values
  ('Single Room Design', 'single-room-design', 'design', '$650', 65000,
   'Full room design with custom layout, inspiration boards, and curated shopping list.',
   'virtual', 120, 4.9, 127,
   array['Custom mood board', 'Shopping list with links', 'Floor plan layout', 'Color palette guide'],
   '/images/services/single-room-design.jpg'),
  ('Home Staging', 'home-staging', 'staging', '$6,000', 600000,
   'Whole-home staging for listings up to ~2,000 sq ft with designer-selected furnishings.',
   'in_person', 480, 5.0, 89,
   array['Furniture rental coordination', 'Professional styling', 'Photography-ready setup', 'Quick turnaround'],
   '/images/services/home-staging.jpg'),
  ('Event Setup', 'event-setup', 'events', '$2,400', 240000,
   'Décor concept, layout, and on-site styling for gatherings and celebrations.',
   'in_person', 240, 4.8, 64,
   array['Theme consultation', 'Décor setup', 'On-site coordination', 'Breakdown service'],
   '/images/services/event-setup.jpg'),
  ('Color Consultation', 'color-consultation', 'consultation', '$250', 25000,
   'Virtual or in-person palette planning with follow-up swatches and notes.',
   'virtual', 60, 4.9, 201,
   array['Video consultation', 'Custom palette', 'Paint recommendations', 'Follow-up support'],
   '/images/services/color-consultation.jpg'),
  ('In-Home Consultation', 'in-home-consultation', 'consultation', '$200 / hour', null,
   'Hands-on walkthrough credited toward your project if you continue with us.',
   'in_person', 60, 4.9, 73,
   array['Space audit', 'Priority recommendations', 'On-site measurements'],
   '/images/services/in-home-consultation.jpg'),
  ('Installation Oversight', 'installation-oversight', 'implementation', '$1,500', 150000,
   'Project management during deliveries and install to make sure every detail lands perfectly.',
   'in_person', 360, 5.0, 58,
   array['Vendor coordination', 'Furniture placement', 'Punch list management'],
   '/images/services/installation-oversight.jpg'),
  ('White-Glove Sourcing', 'white-glove-sourcing', 'implementation', '$3,000', 300000,
   'Premium vendor search and quality-checked sourcing for elevated pieces and finishes.',
   'hybrid', 480, 5.0, 42,
   array['Curated vendor list', 'Sample management', 'Quality assurance'],
   '/images/services/white-glove-sourcing.jpg')
on conflict (slug) do nothing;

